import keys as ks
import conj_funcs as cf


dicts = {
    "presente_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "llueve",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "imperfecto_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "llovía",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "pretérito_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "llovió",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "futuro_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "lloverá",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "condicional_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "llovería",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "pretérito_perfecto_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "ha llovido",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "pluscuamperfecto_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "había llovido",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "futuro_perfecto_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "habrá llovido",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "condicional_perfecto_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "habría llovido",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "presente_subjuntivo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "llueva",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "imperfecto_subjuntivo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "lloviera o lloviese",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "futuro_subjuntivo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "lloviere",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "pretérito_perfecto_subjuntivo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "haya llovido",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "pluscuamperfecto_subjuntivo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "hubiera o hubiese llovido",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "futuro_perfecto_subjuntivo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "hubiere llovido",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
    "afirmativo_imperativo": {
        "(tú)": "–",
        "(usted)": "–",
        "(nosotros/as)": "–",
        "(vosotros/as)": "–",
        "(ustedes)": "–",
        "(vos)": "–",
    },
    "negativo_imperativo": {
        "(tú)": "–",
        "(usted)": "–",
        "(nosotros/as)": "–",
        "(vosotros/as)": "–",
        "(ustedes)": "–",
        "(vos)": "–",
    },
    "pretérito_anterior_indicativo": {
        "yo": "–",
        "tú": "–",
        "él, ella, Vd": "hubo llovido",
        "nosotros/as": "–",
        "vosotros/as": "–",
        "ellos/as, Vds": "–",
        "vos": "–",
    },
}

conj_dict = {}

# output = cf.prettify_dict(dicts['presente_indicativo'])
# print(output)
cd = dicts["presente_indicativo"]
print(cd)
print(cf.get_conj(dicts, "llover", "presente_indicativo"))
